<Project>
    <PropertyGroup>
        <Version>0.3.3</Version>
        <PackageReleaseNotes>
### Changed

* [Allow use of asterisks for list items, and support nested lists](https://github.com/ionide/KeepAChangelog/pull/42)
        </PackageReleaseNotes>
    </PropertyGroup>

   <Import Project="../Directory.Build.props" />
</Project>
