<Project>
    <PropertyGroup>
        <Version>0.3.2</Version>
        <PackageReleaseNotes>
### Fixed

* [Update KeepAChangelogParser to 2.0.1](https://github.com/ionide/KeepAChangelog/pull/41)
        </PackageReleaseNotes>
    </PropertyGroup>

   <Import Project="../Directory.Build.props" />
</Project>
