name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
    - name: Restore
      run: dotnet restore
    - name: Run Build
      run: dotnet build --no-restore -c Release
    - name: Pack
      run: dotnet pack --no-restore -c Release -o packages
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: packages
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: packages/*.nupkg
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
    - name: Push packages
      run: dotnet nuget push packages/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}